class GeometryConfig
  TEAM_TYPE_Y_OFFSET = 390
  TEAM_GROUP_X_OFFSET = 190
  TEAM_Y_OFFSET = 40
  TEAM_BREAKDOWN_X_OFFSET = 140
  TEAM_BREAKDOWN_MEMBER_Y_OFFSET = 40
  TEAM_BREAKDOWN_ROW_HEIGHT = 500
  TEAM_BREAKDOWN_TEAMS_PER_ROW = 12
end
